# Generated by Django 5.0.1 on 2024-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
